name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Rust
        uses: dtolnay/gh-action-rust-toolchain@stable
        with:
          toolchain: stable

      - name: Install target
        run: rustup target add x86_64-unknown-linux-gnu

      - name: Build release
        run: cargo build --release --workspace --locked --target x86_64-unknown-linux-gnu

      - name: Create release
        id: create_release
        uses: actions/create-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false

      - name: Upload binary
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: target/x86_64-unknown-linux-gnu/release/element-bin
          asset_name: element-bin-${{ github.ref_name }}-linux-x86_64
          asset_content_type: application/octet-stream
